name: posts_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # di
  get_it: ^7.6.4
  # generating a string to state sha1
  crypto: ^3.0.3
  # html parse
  flutter_widget_from_html_core: ^0.14.7
  # bloc state manager
  flutter_bloc: ^8.1.3
  # sms auto fill
  pinput: ^3.0.1
  # hive
  hive: ^2.2.3
  # equatable
  equatable: ^2.0.5
  # rest api
  dio: ^5.3.4
  dio_retry_plus: ^2.0.4
  # svg
  flutter_svg: ^2.0.9
  # path
  path_provider: ^2.1.1
  # box
  gap: ^3.0.1
  # native splash
  flutter_native_splash: ^2.3.6
  # url launchers
  url_launcher: ^6.2.1
  # chuck
  chuck_interceptor: ^2.0.6+1
  # permission
  permission_handler: ^11.0.1
  # snack bar
  flash: ^3.0.5+2
  # intl utils
  intl_utils: ^2.8.5
  # share
  share_plus: ^7.2.1
  go_router: ^12.1.1
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  bloc_test: ^9.1.5
  mockito: ^5.4.3

flutter:
  uses-material-design: true


  assets:
    - assets/locale/
    - assets/fonts/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf